#!/usr/bin/env python3
"""Copy the files hugo-base owns into a consuming site.

Usage:
    python3 tools/sync.py --base <hugo-base dir> --site <site dir> [--check]

The manifest is <base>/tools/managed-files.toml. Copies are verbatim, apart
from __HUGO_BASE_VERSION__ in entries marked substitute, so --check is a plain
comparison. The paths written are recorded in <site>/.hugo-base-managed, which
lets a later sync delete files that left the manifest.

--check writes nothing and exits 1 if anything is missing, stale or orphaned,
printing a diff. That is what CI runs, so a hugo-base bump carries its updated
rules into the same pull request.

Standard library only, so it runs anywhere Hugo does.
"""

from __future__ import annotations

import argparse
import difflib
import os
import re
import sys
import tomllib
from pathlib import Path

MODULE_PATH = "github.com/bradryanbice/hugo-base"
STATE_FILE = ".hugo-base-managed"
STATE_HEADER = (
    "# Files managed by hugo-base. Generated by ./hugo-base.sh sync.\n"
    "# Do not edit this file or the files it lists.\n"
)
VERSION_PLACEHOLDER = "__HUGO_BASE_VERSION__"


def site_version(site: Path) -> str:
    """The hugo-base version the site pins, or "main" when it uses a local copy."""
    go_mod = site / "go.mod"
    if go_mod.is_file():
        pattern = re.compile(rf"^\s*(?:require\s+)?{re.escape(MODULE_PATH)}\s+(v\S+)", re.M)
        found = pattern.search(go_mod.read_text(encoding="utf-8"))
        if found:
            return found.group(1)
    return "main"


def manifest_entries(base: Path):
    """Yield (source file, target path relative to the site, mode, substitute)."""
    manifest = base / "tools" / "managed-files.toml"
    if not manifest.is_file():
        sys.exit(f"error: no manifest at {manifest}")
    data = tomllib.loads(manifest.read_text(encoding="utf-8"))
    for entry in data.get("files", []):
        source = base / entry["source"]
        target = entry["target"]
        mode = entry.get("mode")
        substitute = entry.get("substitute", False)
        if "glob" in entry:
            if not source.is_dir():
                sys.exit(f"error: manifest source is not a directory: {source}")
            for path in sorted(source.glob(entry["glob"])):
                if path.is_file():
                    yield path, f"{target}/{path.relative_to(source)}", mode, substitute
        else:
            if not source.is_file():
                sys.exit(f"error: manifest source is missing: {source}")
            yield source, target, mode, substitute


def render(source: Path, substitute: bool, version: str) -> str:
    text = source.read_text(encoding="utf-8")
    if substitute:
        text = text.replace(VERSION_PLACEHOLDER, version)
    return text


def previous_state(site: Path) -> list[str]:
    state = site / STATE_FILE
    if not state.is_file():
        return []
    lines = state.read_text(encoding="utf-8").splitlines()
    return [line.strip() for line in lines if line.strip() and not line.startswith("#")]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", required=True, type=Path, help="the hugo-base module directory")
    parser.add_argument("--site", required=True, type=Path, help="the site to sync into")
    parser.add_argument("--check", action="store_true", help="report staleness, write nothing")
    parser.add_argument("--version", help="override the hugo-base version written into files")
    args = parser.parse_args()

    base = args.base.resolve()
    site = args.site.resolve()
    version = args.version or site_version(site)

    wanted: dict[str, tuple[Path, str | None, bool]] = {}
    for source, target, mode, substitute in manifest_entries(base):
        wanted[target] = (source, mode, substitute)

    problems: list[str] = []
    written: list[str] = []

    for target in sorted(wanted):
        source, mode, substitute = wanted[target]
        expected = render(source, substitute, version)
        destination = site / target
        current = destination.read_text(encoding="utf-8") if destination.is_file() else None

        if args.check:
            if current is None:
                problems.append(f"missing: {target}")
            elif current != expected:
                diff = difflib.unified_diff(
                    current.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=f"{target} (in site)",
                    tofile=f"{target} (hugo-base {version})",
                )
                problems.append(f"stale: {target}\n" + "".join(diff))
            continue

        if current != expected:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(expected, encoding="utf-8")
            print(f"wrote   {target}")
        else:
            print(f"ok      {target}")
        if mode:
            os.chmod(destination, int(mode, 8))
        written.append(target)

    orphans = [path for path in previous_state(site) if path not in wanted]
    for path in orphans:
        if args.check:
            problems.append(f"no longer managed, remove it: {path}")
            continue
        target = site / path
        if target.is_file():
            target.unlink()
            print(f"removed {path}")

    if args.check:
        expected_state = STATE_HEADER + "".join(f"{path}\n" for path in sorted(wanted))
        state_path = site / STATE_FILE
        actual_state = state_path.read_text(encoding="utf-8") if state_path.is_file() else None
        if actual_state != expected_state:
            problems.append(f"stale: {STATE_FILE}")

        if problems:
            print("Managed files are out of date:\n", file=sys.stderr)
            for problem in problems:
                print(problem, file=sys.stderr)
            print(
                f"\n::error::run ./hugo-base.sh sync and commit the result "
                f"(hugo-base {version})",
                file=sys.stderr,
            )
            return 1
        print(f"Managed files are current (hugo-base {version}).")
        return 0

    (site / STATE_FILE).write_text(
        STATE_HEADER + "".join(f"{path}\n" for path in sorted(wanted)), encoding="utf-8"
    )
    print(f"\nSynced {len(written)} file(s) from hugo-base {version}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
